// NOTE: This file has been automatically generated by github.com/aacfactory/gcg. Dont Edit it.

package accounts

import (
	"context"

	"github.com/aacfactory/errors"
	"github.com/aacfactory/fns/service"
	"github.com/aacfactory/fns/service/documents"
	"github.com/aacfactory/fns/service/validators"
)

const (
	_name     = "accounts"
	_createFn = "create"
)

func Create(ctx context.Context, argument CreateArgument) (result *CreateResult, err errors.CodeError) {
	endpoint, hasEndpoint := service.GetEndpoint(ctx, _name)
	if !hasEndpoint {
		err = errors.NotFound("endpoint was not found").WithMeta("name", _name)
		return
	}
	fr := endpoint.Request(ctx, _createFn, service.NewArgument(argument))
	handled := CreateResult{}
	hasResult, handleErr := fr.Get(ctx, &handled)
	if handleErr != nil {
		err = handleErr
		return
	}
	if hasResult {
		result = &handled
	}
	return
}

func Service() (svc service.Service) {
	components := []service.Component{}
	svc = &_service_{
		Abstract: service.NewAbstract(
			_name,
			false,
			components...,
		),
	}
	return
}

type _service_ struct {
	service.Abstract
}

func (svc *_service_) Handle(ctx context.Context, fn string, argument service.Argument) (v interface{}, err errors.CodeError) {
	switch fn {
	case _createFn:
		// argument
		arg := CreateArgument{}
		scanErr := argument.As(&arg)
		if scanErr != nil {
			err = errors.BadRequest("accounts: scan request argument failed").WithCause(scanErr).WithMeta("service", _name).WithMeta("fn", _createFn)
			return
		}
		validateErr := validators.Validate(arg)
		if validateErr != nil {
			err = errors.BadRequest("accounts: invalid request argument").WithMeta("service", _name).WithMeta("fn", _createFn).WithCause(validateErr)
			return
		}
		// handle
		v, err = create(ctx, arg)
		break
	default:
		err = errors.NotFound("accounts: fn was not found").WithMeta("service", _name).WithMeta("fn", fn)
		break
	}
	return

}

func (svc *_service_) Document() (doc service.Document) {
	sd := documents.NewService(_name, "Accounts service")
	sd.AddFn(
		"create", "Create account", "Create an account\n----------\nerrors:\n| Name                     | Code    | Description                   |\n|--------------------------|---------|-------------------------------|\n| accounts_create_failed   | 500     | create account failed         |", false, false,
		documents.Struct("main/modules/accounts", "CreateArgument", "Create account argument", "Create account argument").
			AddProperty("username",
				documents.String().SetTitle("username").SetDescription("account's username").AsRequired(`validate:"required" message:"username is invalid"`),
			).
			AddProperty("password",
				documents.String().SetTitle("password").SetDescription("account's password").AsRequired(`validate:"required" message:"password is invalid"`),
			),
		documents.Struct("main/modules/accounts", "CreateResult", "Create account result", "Create account result").
			AddProperty("id",
				documents.Int().SetTitle("id").SetDescription("account id"),
			),
	)
	doc = sd
	return
}
