// NOTE: This file has been automatically generated by github.com/aacfactory/gcg. Dont Edit it.

package modules

import (
	"github.com/aacfactory/eventstore/modules/accounts"
	"github.com/aacfactory/eventstore/modules/events"
	"github.com/aacfactory/fns/service"
)

func Services() (services []service.Service) {
	services = append(
		services,
		dependencies()...,
	)
	services = append(
		services,
		accounts.Service(),
		events.Service(),
	)
	return
}
